# see https://s.apache.org/asfyaml
publish:
  whoami: asf-site

github:
  rulesets:
    - name: "Default Branch Protection"
      type: branch
      branches:
        includes:
          - "~DEFAULT_BRANCH"
      restrict_deletion: true
      restrict_force_push: true
